language: node_js
node_js:
  - 8
  - 10
env:
  - secure: "VHx2bdD5gM10OHy5U2MBXWT7IyNod01wsFXkvnl7Ye+mn0M0+mp8YFuT6edHFJc/Rjg+Vm+LLlDT5+bnqa1IX1cEvScWdETr8n+SuPCEqkmIn2ryBOyLhJaOxI9jvqDqX0sr1tH/O1KKxHMit6GrwMZwNv1CQloSCJZEjD+PF28u5ZMnTPv4UVaUak1QPdLgO3VuF+uRHhPrl84Od5+m98A+j/RYs7C9TOqL9Lnxsu9hNgp/Gw31YRzTSaOVqqjd2QfhpRt2ScoJrfJh0twMjlG4n25JZfuxGWjT9DzoBlWK3jkglr02r1vJuUGQlvR0a4P0EcI3HmUiijBZskzy8v8DIlsZOaVvn0WS8rWHf95kxzMwtg1MX53/j0RQtCdHuKNo+25OSY3GdmiS2CYTy5dsxzgcm13ebtIiZHRLqPQqdYqvM7jUCYU4qgOnCpWNdaWUhVDmR4X011qsM7cJdazW4INgxg8EJlp/6BNLhJsPvjQK6nzYKYEUhr3CQ0ZlUOswTOLkuwzCwcX2OIkO76MlNy/sj+R3aWhtrd/IYdLqqcV29iy9xS9GD30zmICvSAb6VYNqetzkl+WvG25+DIJrvle+FiZyj+aBGLCkj9Z3aveUvxa22uO61hO6A9qIncu/uJkr5Ecyn2pyI0jAXytLvfhSIuAxNCA3o5HebAU="
  - secure: "ZP0Lx0pNvKc/rtIoDzxB5fTcTw0q7nsgQ47Eh7GiqktxXDWT7jPwmjDHn8LhDJmzCResrAYiJG9i1u98rh+Gq8ABt+v7mTM/x1e5ag5c0CJOyyFwIvowtqmzOPEw83TtZKZ5Q1cekFLU/D5xK61JKvGKEwua6Ub6z8n+vR28uBH7rCKlRCMrdWPYxiu8XHlOeQmNMVmWoqBGnbsyVO67UIAbuAv5hmFuuFzoOFgyZ4/fAcmEsWKKrTA5GdxvtWVVdqHX61HTYAgO/JfCChCzqtOw3ZMY3egXJd4Coix7deKBt7W24SdPGmUBQq4xm//tF+Otun6KygzeaNbPlq6X2sjrSqXIzJGB7+LZn3mfQkM4DKw+MpOcDYt6tO00mIrUfy9ULOkG9FX8ZG6PYARY3ptaRnWsuAfrU3coTGN3+bvoPP1Rcdi2wB0DEJ6kcMoQWEPFs+nTWgeCSIQ3i+hAkBdy3Czx5M48IlVzzyDu0W6E0j1xVYDq8FwD3TOhJg4lJWSiBl/8zmkEE9ii/OhWOQD/I1bgtf/3emsBs8vWbiGJ3hhXCFIurc0i7KUzBps6gcm5nUBihQ0yrZOsfbE8o7BlDEF4RPZrEBTcZ2X5ajCXXTp7fvYIDSuX1Hfg2D0oYOMyr7HY4nTPcO+8dhIF1AdRZ0iuyUVVjifahch4N3I="
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: Laboratoria/curricula-js
    all_branches: true
